import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BlogContextProvider from "@/context/BlogContext";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="max-w-[1500px] mx-auto text-[#000] bg-[#ebb8c2] px-[0.8rem] sm:px-[2rem] md:px-[3rem] lg:px-[5rem] xl:px-[8rem]"
      >
        <BlogContextProvider>
          <ToastContainer />
          <Navbar />
          {children}
        </BlogContextProvider>
      </body>
    </html>
  );
}
